name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending
categories:
  - title: ":boom: Breaking Change :boom:"
    labels:
      - "breaking-change"
  - title: ":zap: Enhancments :zap:"
    labels:
      - "enhancement"
  - title: ":sparkles: New Features :sparkles:"
    labels:
      - "feature"
  - title: ":bug: Bug Fixes :bug:"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/FutureTense/keymaster/$RESOLVED_VERSION/total.svg)](https://github.com/FutureTense/keymaster/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Wiki](https://github.com/FutureTense/keymaster/wiki)
  - [Submit bugs/feature requests](https://github.com/FutureTense/keymaster/issues)
