input_boolean:
    allow_automation_execution:
        name: 'Allow Automation'
        initial: off

binary_sensor:

    - platform: mqtt
      name: ozw_network_status
      state_topic: OpenZWave/1/status/
      value_template: >
          {{ "on" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "off" }}
      json_attributes_topic: OpenZWave/1/status/
      device_class: "connectivity"

automation:
    - alias: open_zwave_network_down
      initial_state: true
      trigger:
        - platform: state
          entity_id: binary_sensor.ozw_network_status
          to: "off"
      action:
        - service: homeassistant.turn_off
          entity_id: input_boolean.allow_automation_execution

    - alias: open_zwave_network_up
      initial_state: true
      trigger:
        - platform: homeassistant
          event: start
        - platform: state
          entity_id: binary_sensor.ozw_network_status
          to: "on"
      condition:
        - condition: state
          entity_id: binary_sensor.ozw_network_status
          state: "on"
      action:
        - service: homeassistant.turn_on
          entity_id: input_boolean.allow_automation_execution
