[tox]
requires =
    tox>=4.2
    tox-uv>=1.11.3
    tox-gh-actions>=3.2.0
envlist = py314, lint
skip_missing_interpreters = True
skipsdist = True

[gh-actions]
python =
    3.14: py314, lint

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_test.txt
commands =
    pytest --timeout=30 --cov=custom_components/keymaster --cov-report=xml {posargs}

[testenv:lint]
deps =
    -r{toxinidir}/requirements_lint.txt
commands =
    ruff check .
    ruff format --check .
    mypy .
    codespell custom_components/keymaster tests
