## WARNING ##
# This file is auotmaticly generated, any changes
# will be overwritten.

##################################################
################  COMMON ENTITIES  ###############
##################################################

############  timer:  #####################  
timer:

  LOCKNAME_refresh_lock_node:
    duration: '00:15:00'

###############  input_text:  #################
input_text:
  LOCKNAME_status_report:
    name: LOCKNAME Status report

###############  input_number:  #################
input_number:
  LOCKNAME_lock_command:
    name: CASE_LOCK_NAME Lock command
    min: 0
    max: 999

  LOCKNAME_lock_user:
    name: CASE_LOCK_NAME Lock user
    min: 0
    max: 999

###############  input_boolean:  #################
input_boolean:
  LOCKNAME_lock_notifications:
    name: CASE_LOCK_NAME Lock Notifications
  LOCKNAME_dooraccess_notifications:
    name: CASE_LOCK_NAME Door Notifications
  LOCKNAME_garageacess_notifications:
    name: CASE_LOCK_NAME Garage Notifications
  LOCKNAME_reset_lock:
    name: CASE_LOCK_NAME reset lock

###################  sensor:  ####################
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"

  - platform: template
    sensors:
      LOCKNAME_ac_last_changed:
        friendly_name: CASE_LOCK_NAME AC Last Changed From Present
        unit_of_measurement: "seconds"
        value_template: >-
          {% set CONTROL = 'input_number.LOCKNAME_lock_command' %}
          {% set CONTROLlc = states.input_number[CONTROL.split('.')[-1]].last_changed %}
          {{ (as_timestamp(now()) - as_timestamp(CONTROLlc)) | float }}

      LOCKNAME_uc_last_changed:
        friendly_name: CASE_LOCK_NAME UC Last Changed From Present
        unit_of_measurement: "seconds"
        value_template: >-
          {% set CONTROL = 'input_number.LOCKNAME_lock_user' %}
          {% set CONTROLlc = states.input_number[CONTROL.split('.')[-1]].last_changed %}
          {{ (as_timestamp(now()) - as_timestamp(CONTROLlc)) | float }}

###################  script    :  ####################
script:
  LOCKNAME_reset_lock:
    sequence:
      - service: script.LOCKNAME_manual_notify
        data_template:
          title: "reset"
          message: "LOCKNAME"

  LOCKNAME_conditional_notify:
    sequence:
      - condition: template
        value_template: >-
          {% set inputbool = boolean %}
          {% if states(inputbool) == 'on'%}
            true
          {% else %}
            false
          {% endif %}
      - service: script.LOCKNAME_manual_notify
        data_template:
          title: "{{title}}"
          message: "{{message}}"

  LOCKNAME_refreshnodeinfo:
    description:  'Send MQTT RefreshNodeInfo command'
    sequence:
      - service: system_log.write
        data_template:
          message: "LOCKNAME_TEMPLATENUM started noderefreshinfo: {{ now() }}"
          level: debug  
      - service: mqtt.publish
        data:
          topic: 'OpenZWave/1/command/refreshnodeinfo/'
          payload: >-
            {% set node_id = state_attr('LOCKENTITYNAME','node_id') %}
            { "node": {{ node_id }} }
          retain: true
          
  LOCKNAME_refresh_codes:
    description:  'Refreshes lock user codes'
    sequence:
      - service: system_log.write
        data_template:
          message: "refresh user codes: {{ now() }}"
          level: debug
      # - service: mqtt.publish
      #   data:
      #     topic: 'OpenZWave/1/command/refreshnodeinfo/'
      #     payload: >-
      #       {% set node_id = state_attr('LOCKENTITYNAME','node_id') %}
      #       { "node": {{ node_id }} }
      #     retain: true

###################  automation:  ####################
automation:
          
  - alias: LOCKNAME_refresh_lock_node_finished
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.LOCKNAME_refresh_lock_node
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
    action:
      - service: script.LOCKNAME_refreshnodeinfo

  - alias: CASE_LOCK_NAME Lock Command
    trigger:
      platform: state
      entity_id: SENSORALARMTYPE
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.LOCKNAME_lock_command
          value: >-
            {{ states('SENSORALARMTYPE') | int}}

  - alias: CASE_LOCK_NAME User Command
    trigger:
      platform: state
      entity_id: SENSORALARMLEVEL
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.LOCKNAME_lock_user
          value: >-
            {{ states.SENSORALARMLEVEL.state | int}}

  - alias: CASE_LOCK_NAME RF Locked State Changed
    trigger:
      platform: state
      entity_id: LOCKENTITYNAME
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
      - condition: template
        value_template: >-
          {% set lockuser =  states.SENSORALARMLEVEL.state | int %}
          {% set lockcmd = states.SENSORALARMTYPE.state | int %}
          {% set timediff = (as_timestamp(now()) - as_timestamp(states.SENSORALARMTYPE.last_changed)) | float %}
          {{ lockuser | int == 0 and timediff > 2 }}
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.LOCKNAME_lock_command
          value: >-
            {% set lockcmd = states.SENSORALARMTYPE.state | int %}
            {% set lockstate = states.LOCKENTITYNAME.state %}
            {% if (lockstate == 'locked') %}
               66
            {% elif (lockstate == 'unlocked') %}
               67
            {% else %}
               {{ lockcmd | int}}
            {% endif %}


  # {% set doordiff = as_timestamp(now()) - as_timestamp(states.lock.be666zp_connect_smart_deadbolt_locked.last_changed) %}
  # {% set contdiff = as_timestamp(now()) - as_timestamp(states.sensor.be666zp_connect_smart_deadbolt_access_control.last_changed) %}
  # {% set atv = 24 if (doordiff) < 15 and (contdiff) > 15 and (states.lock.be666zp_connect_smart_deadbolt_locked.state) == 'locked' else alarm_type_value %}
  # {% set atv = 25 if (doordiff) < 15 and (contdiff) > 15 and (states.lock.be666zp_connect_smart_deadbolt_locked.state) == 'unlocked' else alarm_type_value %}

  - alias: CASE_LOCK_NAME Status Report
    trigger:
      platform: state
      entity_id: input_number.LOCKNAME_lock_command, input_number.LOCKNAME_lock_user
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
      - condition: template
        value_template: "{{ states('SENSORALARMTYPE') != 0 }}"
    action:
      - service: input_text.set_value
        data_template:
          entity_id: input_text.LOCKNAME_status_report
          value: >-
            {% set UC = 'SENSORALARMLEVEL' %}
            {% set AC = 'SENSORALARMTYPE' %}
            {% set UClc = states.sensor[UC.split('.')[-1]].last_changed %}
            {% set AClc = states.sensor[AC.split('.')[-1]].last_changed %}

            {% set usercode_value = states.input_number.LOCKNAME_lock_user.state | int | string  %}
            {% set alarm_type_value = states.input_number.LOCKNAME_lock_command.state | int | string %}

            {% set atv = 0 %}
            {% if (alarm_type_value | int == 66 or alarm_type_value | int == 67) %}
              {% if 'alarm_type' in AC %}
                 {% set atv = alarm_type_value | int - 42 %}
              {% elif 'access_control' in AC %}
                 {% set atv = alarm_type_value | int - 63 %}
              {% endif %}
            {% endif %}
            {% if atv != 0 %}
               {% set alarm_type_value = atv %}
            {% endif %}

            {% set alarm_type_value = alarm_type_value | string %}

            {% if 'alarm_type' in AC %}
              {% set alarm_type_general_actions = {
                '999':'Kwikset',
                '0':'No Status Reported',
                '9':'Lock Jammed',
                '17':'Keypad Lock Jammed',
                '21':'Manual Lock',
                '22':'Manual Unlock',
                '23':'RF Lock Jammed',
                '24':'RF Lock',
                '25':'RF Unlock',
                '26':'Auto Lock Jammed',
                '27':'Auto Lock',
                '32':'All Codes Deleted',
                '161':'Bad Code Entered',
                '167':'Battery Low',
                '168':'Battery Critical',
                '169':'Battery Too Low To Operate Lock' } %}
              {% set alarm_type_lock_actions = {
                '16':'Keypad Unlock',
                '18':'Keypad Lock',
                '19':'Keypad Unlock',
                '162':'Lock Code Attempt Outside of Schedule' } %}
              {% set alarm_type_code_actions = {
                '33':'Code Deleted',
                '112':'Code Changed',
                '113':'Duplicate Code' } %}
            {% elif 'access_control' in AC %}
              {% set alarm_type_general_actions = {
                '999':'Schlage',
                '1':'Manual Lock',
                '2':'Manual Unlock',
                '3':'RF Lock',
                '4':'RF Unlock',
                '7':'Manual not fully locked',
                '8':'RF not fully locked',
                '9':'Auto Lock locked',
                '10':'Auto Lock not fully locked',
                '11':'Lock Jammed',
                '16':'Keypad temporary disabled',
                '17':'Keypad busy' } %}
              {% set alarm_type_lock_actions = {
                '5':'Keypad Lock',
                '6':'Keypad Unlock' } %}
              {% set alarm_type_code_actions = {
                '12':'All User Codes Deleted',
                '13':'Single Code Deleted',
                '14':'New User Code Added',
                '18':'New Program Code Entered',
                '15':'Duplicate Code' } %}
            {% endif %}
            {% if alarm_type_value in alarm_type_code_actions %}
              {{alarm_type_value}};{{ alarm_type_code_actions[alarm_type_value] }};{{usercode_value}}
            {% elif alarm_type_value in alarm_type_lock_actions  %}
              {{alarm_type_value}};{{ alarm_type_lock_actions[alarm_type_value] }};{{usercode_value}}
            {% elif alarm_type_value in alarm_type_general_actions %}
              {{alarm_type_value}};{{ alarm_type_general_actions[alarm_type_value] }};{{usercode_value}}
            {% else %}
              {{alarm_type_value}};{{alarm_type_value}}-Unknown Alarm Type Value;{{usercode_value}}
            {% endif %}

  - alias: CASE_LOCK_NAME Lock Notifications
    trigger:
      platform: state
      entity_id: input_text.LOCKNAME_status_report
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
      - condition: template
        value_template: >-
          {% set report = states.input_text.LOCKNAME_status_report.state %}
          {% set a = report.split(';') %}
          {% if (a|length) != 3 or (a[2] == "0") %} 
            {{ true }}
          {% else %}
            {{ true }}
          {% endif %}
    action:
      - service: script.LOCKNAME_conditional_notify
        data_template:
          boolean: input_boolean.LOCKNAME_lock_notifications
          title: CASE_LOCK_NAME
          message: >-
            {% set report = states.input_text.LOCKNAME_status_report.state %}
            {% set a = report.split(';') %}
            {{ a[1] }}

  - alias: CASE_LOCK_NAME User Notifications
    trigger:
      platform: state
      entity_id: input_text.LOCKNAME_status_report
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
      - condition: template
        value_template: >-
          {% set report = states.input_text.LOCKNAME_status_report.state %}
          {% set a = report.split(';') %}
          {% if (a|length) == 3 and (a[2] | int > 0) %} 
            {{ true }}
          {% else %}
            {{ false }}
          {% endif %}
      - condition: template
        value_template: >-
          {% set report = states.input_text.LOCKNAME_status_report.state %}
          {% set a = report.split(';') %}
          {% set entity_id = 'notify_LOCKNAME_' + a[2] %}
          {% set notify = states['input_boolean'][entity_id].state %}
          {{ notify == "on" }}
    action:
      - service: script.LOCKNAME_manual_notify
        data_template:
          title: >-
            {% set report = states.input_text.LOCKNAME_status_report.state %}
            {% set a = report.split(';') %}
            {{ a[1] }}
          message: >-
            {% set report = states.input_text.LOCKNAME_status_report.state %}
            {% set a = report.split(';') %}
            {% set entity_id = 'input_text.LOCKNAME_name_' + a[2] %}
            {% set user = states(entity_id) %}
            {{ user }}

  - alias: CASE_LOCK_NAME Sensor Close
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
    trigger:
      entity_id: DOORSENSORENTITYNAME
      platform: state
      to: "off"
    action:
      - service: script.LOCKNAME_conditional_notify
        data_template:
          boolean: input_boolean.LOCKNAME_dooraccess_notifications
          title: CASE_LOCK_NAME
          message: "Closed"

  - alias: CASE_LOCK_NAME Sensor Opened
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
    trigger:
      entity_id: DOORSENSORENTITYNAME
      platform: state
      to: "on"
    action:
      - service: script.LOCKNAME_conditional_notify
        data_template:
          boolean: input_boolean.LOCKNAME_dooraccess_notifications
          title: CASE_LOCK_NAME
          message: "Opened"

  - alias: CASE_LOCK_NAME Changed Code
    trigger:
      entity_id: INPUTLOCKPINHEADER
      platform: state
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
      - condition: template
        value_template: >-
          {% set object_id = trigger.to_state.object_id %}
          {% set index = object_id.rfind('_') + 1 %}
          {% set code_slot = object_id[index:] %}
          {% set b = 'input_boolean.enabled_LOCKNAME_' + code_slot | string %}
          {{ is_state(b, 'on') and (trigger.from_state.state != trigger.to_state.state)}}
    action:
      - service: persistent_notification.create
        data_template:
          title: CASE_LOCK_NAME LOCK MANAGER
          message: >-
            {% set object_id = trigger.to_state.object_id %}
            {% set index = object_id.rfind('_') + 1 %}
            {% set code_slot = object_id[index:] %}
            {{ 'You changed the PIN for code  ' + code_slot | string + '. Please enable it in order to make it active.'}}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {% set object_id = trigger.to_state.object_id %}
            {% set index = object_id.rfind('_') + 1 %}
            {% set code_slot = object_id[index:] %}
            {{ 'input_boolean.enabled_LOCKNAME_' + code_slot | string }}

  - alias: CASE_LOCK_NAME Reset
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
    trigger:
      entity_id: input_boolean.LOCKNAME_reset_lock
      platform: state
      from: "off"
      to: "on"
    action:
      - service: script.LOCKNAME_reset_lock
      - service: input_boolean.turn_off
        entity_id: input_boolean.LOCKNAME_reset_lock

  # - alias: CASE_LOCK_NAME Clear Code
  #   trigger:
  #     entity_id: ACTIVELOCKHEADER
  #     platform: state
  #     to: "off"
  #   condition:
  #     - condition: state
  #       entity_id: "binary_sensor.allow_automation"
  #       state: "on"
  #   action:
  #     - choose:
  #         - conditions: >
  #             {{ USINGOZW }}
  #         # this comment preserves formating
  #           sequence:
  #             - service: ozw.clear_usercode
  #               data_template:
  #                 entity_id: LOCKENTITYNAME
  #                 code_slot: >-
  #                   {% set object_id = trigger.to_state.object_id %}
  #                   {% set index = object_id.rfind('_') + 1 %}
  #                   {% set code_slot = object_id[index:] %}
  #                   {{ code_slot  }}
  #         - conditions: >
  #             {{ USINGOZW == False }}
  #         # this comment preserves formating
  #           sequence:
  #             - service: lock.set_usercode
  #               data_template:
  #                 node_id: >-
  #                   {{ state_attr('LOCKENTITYNAME','node_id') }}
  #                 code_slot: >-
  #                   {% set object_id = trigger.to_state.object_id %}
  #                   {% set index = object_id.rfind('_') + 1 %}
  #                   {% set code_slot = object_id[index:] %}
  #                   {{ code_slot  }}
  #                 usercode: >-
  #                   {{ range(1000, 9999) | random | int }}
  #             - service: lock.clear_usercode
  #               data_template:
  #                 node_id: >-
  #                   {{ state_attr('LOCKENTITYNAME','node_id') }}
  #                 code_slot: >-
  #                   {% set object_id = trigger.to_state.object_id %}
  #                   {% set index = object_id.rfind('_') + 1 %}
  #                   {% set code_slot = object_id[index:] %}
  #                   {{ code_slot  }}

  - alias: CASE_LOCK_NAME Decrement Access Count
    trigger:
      platform: state
      entity_id: input_text.LOCKNAME_status_report
    condition:
      - condition: state
        entity_id: "binary_sensor.allow_automation"
        state: "on"
      - condition: template
        # Check for Keypad Unlock code
        value_template: >-
          {% set report = states.input_text.LOCKNAME_status_report.state %}
          {% set a = report.split(';') %}
          {% if (a|length) == 3 and (a[2] | int > 0) %} 
             {{ (a[0] | int == 19) or (a[0] | int == 6)  }}
          {% else %}
            {{ false }}
          {% endif %}
    action:
      - service: input_number.decrement
        data_template:
          entity_id: >-
            {% set report = states.input_text.LOCKNAME_status_report.state %}
            {% set a = report.split(';') %}
            {{ 'input_number.accesscount_LOCKNAME_' + a[2] }}
