## WARNING ##
# This file is auotmaticly generated, any changes
# will be overwritten.

##################################################
################  COMMON ENTITIES  ###############
##################################################

###############  input_boolean:  #################
input_boolean:
  LOCKNAME_lock_notifications:
    name: CASE_LOCK_NAME Lock Notifications
  LOCKNAME_dooraccess_notifications:
    name: CASE_LOCK_NAME Door Notifications
  LOCKNAME_garageacess_notifications:
    name: CASE_LOCK_NAME Garage Notifications
  LOCKNAME_reset_lock:
    name: CASE_LOCK_NAME reset lock
  keymaster_LOCKNAME_autolock:
    name: "Auto Lock Enabled"
    icon: mdi:key-remove

###################  script:  ####################
script:
  keymaster_LOCKNAME_reset_lock:
    sequence:
      - service: script.keymaster_LOCKNAME_manual_notify
        data_template:
          title: "reset"
          message: "LOCKNAME"

  keymaster_LOCKNAME_reset_codeslot:
    mode: parallel
    fields:
      code_slot:
        description: The code slot to reset
        example: 1
    variables:
      # Constant used later to loop through day specific entities
      days: ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
    sequence:
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.enabled_LOCKNAME_{{ code_slot | string }}"
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.LOCKNAME_name_{{ code_slot | string }}"
          value: ""
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.LOCKNAME_pin_{{ code_slot | string }}"
          value: ""
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.notify_LOCKNAME_{{ code_slot | string }}"
      - service: input_number.set_value
        data_template:
          entity_id: "input_number.accesscount_LOCKNAME_{{ code_slot | string }}"
          value: "0"
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.start_date_LOCKNAME_{{ code_slot | string }}"
          datetime: >-
            {{ now().strftime('%Y-%m-%d 00:00') }}
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.end_date_LOCKNAME_{{ code_slot | string }}"
          datetime: >-
            {{ now().strftime('%Y-%m-%d 00:00') }}
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.daterange_LOCKNAME_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.accesslimit_LOCKNAME_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.reset_codeslot_LOCKNAME_{{ code_slot | string }}"
      # Loop through each day of the week and reset the entities related to each one
      - repeat:
          count: 7
          sequence:
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_start_date_LOCKNAME_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_end_date_LOCKNAME_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_LOCKNAME_{{ code_slot | string }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_inc_LOCKNAME_{{ code_slot | string }}"

  keymaster_LOCKNAME_refreshnodeinfo:
    description: "Send MQTT RefreshNodeInfo command"
    sequence:
      - service: system_log.write
        data_template:
          message: "LOCKNAME_TEMPLATENUM started noderefreshinfo: {{ now() }}"
          level: debug
      - service: mqtt.publish
        data:
          topic: "OpenZWave/1/command/refreshnodeinfo/"
          payload: >-
            {% set node_id = state_attr('LOCKENTITYNAME','node_id') %}
            { "node": {{ node_id }} }
          retain: true

  keymaster_LOCKNAME_start_timer_retry:
    sequence:
      - condition: state
        entity_id: LOCKENTITYNAME
        state: "unlocked"
      - service: timer.cancel
        entity_id: timer.keymaster_LOCKNAME_autolock
      - service: timer.start
        data_template:
          entity_id: timer.keymaster_LOCKNAME_autolock
          duration: 00:00:30

  keymaster_LOCKNAME_start_timer:
    sequence:
      - condition: state
        entity_id: LOCKENTITYNAME
        state: "unlocked"
      - service: timer.cancel
        entity_id: timer.keymaster_LOCKNAME_autolock
      - service: timer.start
        data_template: # if next_dusk happens sooner than next_dawn, then it's daylight
          entity_id: timer.keymaster_LOCKNAME_autolock
          duration: >
            {% if (((as_timestamp(states.sun.sun.attributes.next_dusk)) > (as_timestamp(states.sun.sun.attributes.next_dawn)))) %}
              {{ states('input_text.keymaster_LOCKNAME_autolock_door_time_night')}}
            {% else %}
              {{ states('input_text.keymaster_LOCKNAME_autolock_door_time_day')}}
            {% endif %}

###################  automation:  ####################
automation:
  - alias: CASE_LOCK_NAME Reset Code Slot
    id: CASE_LOCK_NAME Reset Code Slot
    trigger:
      entity_id: INPUT_RESET_CODE_SLOT_HEADER
      platform: state
      to: "on"
    action:
      - service: script.keymaster_LOCKNAME_reset_codeslot
        data_template:
          code_slot: "{{ trigger.entity_id.split('_')[-1] }}"

  - alias: CASE_LOCK_NAME Lock Notifications
    id: CASE_LOCK_NAME Lock Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: LOCKNAME
    condition:
      - condition: state
        entity_id: input_boolean.LOCKNAME_lock_notifications
        state: "on"
    action:
      - service: script.keymaster_LOCKNAME_manual_notify
        data_template:
          title: CASE_LOCK_NAME
          message: "{{ trigger.event.data.action_text }} {% if trigger.event.data.code_slot > 0 %}({{ trigger.event.data.code_slot_name }}){% endif %}"

  - alias: CASE_LOCK_NAME User Notifications
    id: CASE_LOCK_NAME User Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: LOCKNAME
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.code_slot > 0 }}"
      - condition: template
        value_template: "{{ is_state('input_boolean.notify_LOCKNAME_' + trigger.event.data.code_slot | string, 'on') }}"
      - condition: state
        entity_id: input_boolean.LOCKNAME_lock_notifications
        state: "off"
    action:
      - service: script.keymaster_LOCKNAME_manual_notify
        data_template:
          title: CASE_LOCK_NAME
          message: "{{ trigger.event.data.action_text }} ({{ trigger.event.data.code_slot_name }})"

  - alias: CASE_LOCK_NAME Door Open and Close
    id: CASE_LOCK_NAME Door Open and Close
    trigger:
      entity_id: DOORSENSORENTITYNAME
      platform: state
    condition:
      - condition: state
        entity_id: "input_boolean.LOCKNAME_dooraccess_notifications"
        state: "on"
      - condition: template
        value_template: "{{ trigger.from_state.state in ('on', 'off') and trigger.to_state.state in ('on', 'off') }}"
    action:
      - service: script.keymaster_LOCKNAME_manual_notify
        data_template:
          title: CASE_LOCK_NAME
          message: "{% if trigger.to_state.state == 'on' %}Door Opened{% else %}Door Closed{% endif %}"

  - alias: CASE_LOCK_NAME Changed Code
    id: CASE_LOCK_NAME Changed Code
    trigger:
      entity_id: INPUTLOCKPINHEADER
      platform: state
    condition:
      - condition: template
        value_template: >-
          {{
            is_state('input_boolean.enabled_LOCKNAME_' + trigger.entity_id.split('_')[-1], 'on')
            and
            (trigger.from_state.state != trigger.to_state.state)
          }}
    action:
      - service: persistent_notification.create
        data_template:
          title: CASE_LOCK_NAME LOCK MANAGER
          message: >-
            {{ 'You changed the PIN for CASE_LOCK_NAME code slot ' + trigger.entity_id.split('_')[-1] + '. Please enable it in order to make it active.'}}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {{ 'input_boolean.enabled_LOCKNAME_' + trigger.entity_id.split('_')[-1] }}

  - alias: CASE_LOCK_NAME Reset
    id: CASE_LOCK_NAME Reset
    trigger:
      entity_id: input_boolean.LOCKNAME_reset_lock
      platform: state
      from: "off"
      to: "on"
    action:
      - service: script.keymaster_LOCKNAME_reset_lock
      - service: input_boolean.turn_off
        entity_id: input_boolean.LOCKNAME_reset_lock

  - alias: CASE_LOCK_NAME Decrement Access Count
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: LOCKNAME
    condition:
      - condition: template
        # make sure decrementing access entries is enabled
        value_template: "{{ is_state('input_boolean.accesslimit_LOCKNAME_' + trigger.event.data.code_slot | string, 'on') }}"
      - condition: template
        # Check for Keypad Unlock code
        value_template: >-
          {{
            trigger.event.data.code_slot > 0
            and
            (trigger.event.data.action_code is undefined or trigger.event.data.action_code in (6, 19))
          }}
    action:
      - service: input_number.decrement
        data_template:
          entity_id: "{{ 'input_number.accesscount_LOCKNAME_' + trigger.event.data.code_slot | string }}"

  - alias: keymaster_LOCKNAME_locked
    id: keymaster_LOCKNAME_locked
    trigger:
      entity_id: LOCKENTITYNAME
      platform: state
      to: locked
    action:
      - service: timer.cancel
        entity_id: timer.keymaster_LOCKNAME_autolock

  - alias: keymaster_LOCKNAME_unlocked
    id: keymaster_LOCKNAME_unlocked
    trigger:
      entity_id: LOCKENTITYNAME
      platform: state
      to: unlocked
    condition:
      - condition: state
        entity_id: input_boolean.keymaster_LOCKNAME_autolock
        state: "on"
    action:
      - service: script.turn_on
        entity_id: script.keymaster_LOCKNAME_start_timer

  - alias: keymaster_LOCKNAME_timer_finished
    id: keymaster_LOCKNAME_timer_finished
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.keymaster_LOCKNAME_autolock
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ (states('DOORSENSORENTITYNAME') != 'on') }}"
            sequence:
              - service: lock.lock
                entity_id: LOCKENTITYNAME
          - conditions:
              - condition: template
                value_template: "{{ (states('DOORSENSORENTITYNAME') == 'on') }}"
            sequence:
              - service: script.keymaster_LOCKNAME_start_timer_retry

  - alias: keymaster_LOCKNAME_disable_auto_lock
    id: keymaster_LOCKNAME_disable_auto_lock
    trigger:
      entity_id: input_boolean.keymaster_LOCKNAME_autolock
      platform: state
      to: "off"
    action:
      - service: timer.cancel
        entity_id:
          - timer.keymaster_LOCKNAME_autolock
      - service: lock.unlock
        entity_id: LOCKENTITYNAME

  - alias: keymaster_LOCKNAME_enable_auto_lock
    id: keymaster_LOCKNAME_enable_auto_lock
    trigger:
      entity_id: input_boolean.keymaster_LOCKNAME_autolock
      platform: state
      to: "on"
    action:
      - service: timer.cancel
        entity_id:
          - timer.keymaster_LOCKNAME_autolock
      - service: lock.lock
        entity_id: LOCKENTITYNAME

###############  input_text:  #################
input_text:
  LOCKNAME_lockname:
    initial: LOCKNAME
    name: "Lock Name"
  LOCKNAME_PARENTLOCK_parent:
    initial: PARENTLOCK
    name: "Parent lock"

  keymaster_LOCKNAME_autolock_door_time_day:
    name: "Day Auto Lock HH:MM:SS"
    initial: "00:15:00"
  keymaster_LOCKNAME_autolock_door_time_night:
    name: "Night Auto Lock HH:MM:SS"
    initial: "00:05:00"

###################  timer:  ####################
timer:
  keymaster_LOCKNAME_autolock:
    name: "Auto Lock Timer"
