
############  input_number:  #####################  
input_number:
  accesscount_LOCKNAME_TEMPLATENUM:
    name: 'Unlock events'
    min: 0
    max: 100
    step: 1
    mode: box

#################  input_datetime:  ##############  
input_datetime:
  end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: false
    has_date: true
  start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: false
    has_date: true

  sun_start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: true
    has_date: false
  sun_end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: true
    has_date: false

  mon_start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: true
    has_date: false
  mon_end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: true
    has_date: false

  tue_start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: true
    has_date: false
  tue_end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: true
    has_date: false

  wed_start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: true
    has_date: false
  wed_end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: true
    has_date: false

  thu_start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: true
    has_date: false
  thu_end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: true
    has_date: false

  fri_start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: true
    has_date: false
  fri_end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: true
    has_date: false

  sat_start_date_LOCKNAME_TEMPLATENUM:
    name: 'Start'
    has_time: true
    has_date: false
  sat_end_date_LOCKNAME_TEMPLATENUM:
    name: 'End'
    has_time: true
    has_date: false


####################  input_text:  ###############  
input_text:
  LOCKNAME_name_TEMPLATENUM:
    name: 'Name'
  LOCKNAME_pin_TEMPLATENUM:
    name: 'PIN'
    mode: HIDE_PINS

#################  input_boolean: ################  
input_boolean:
  notify_LOCKNAME_TEMPLATENUM:
    name: 'Notifications'
  daterange_LOCKNAME_TEMPLATENUM:
    name: 'Use Date Range'
  enabled_LOCKNAME_TEMPLATENUM:
    name: 'Enabled'
  accesslimit_LOCKNAME_TEMPLATENUM:
    name: 'Enforce PIN limit'
  reset_codeslot_LOCKNAME_TEMPLATENUM:
    name: 'Reset Code Slot'

  sun_LOCKNAME_TEMPLATENUM:
    name: 'Sunday'

  mon_LOCKNAME_TEMPLATENUM:
    name: 'Monday'

  tue_LOCKNAME_TEMPLATENUM:
    name: 'Tuesday'

  wed_LOCKNAME_TEMPLATENUM:
    name: 'Wednesday'

  thu_LOCKNAME_TEMPLATENUM:
    name: 'Thursday'

  fri_LOCKNAME_TEMPLATENUM:
    name: 'Friday'

  sat_LOCKNAME_TEMPLATENUM:
    name: 'Saturday'

  sun_inc_LOCKNAME_TEMPLATENUM:
    name: 'include (on)/exclude (off)'

  mon_inc_LOCKNAME_TEMPLATENUM:
    name: 'include (on)/exclude (off)'

  tue_inc_LOCKNAME_TEMPLATENUM:
    name: 'include (on)/exclude (off)'

  wed_inc_LOCKNAME_TEMPLATENUM:
    name: 'include (on)/exclude (off)'

  thu_inc_LOCKNAME_TEMPLATENUM:
    name: 'include (on)/exclude (off)'

  fri_inc_LOCKNAME_TEMPLATENUM:
    name: 'include (on)/exclude (off)'

  sat_inc_LOCKNAME_TEMPLATENUM:
    name: 'include (on)/exclude (off)'

################  automation: #################  
automation:

- alias: synchronize_codeslot_LOCKNAME_TEMPLATENUM
  initial_state: true
  trigger:
    - platform: state
      entity_id: "binary_sensor.pin_synched_LOCKNAME_TEMPLATENUM"
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: "sensor.LOCKNAME_code_slot_TEMPLATENUM"
  condition:
    - condition: template
      value_template: >-
        {{
          states("sensor.LOCKNAME_code_slot_TEMPLATENUM") != "unavailable"
          and
          trigger.from_state.state != "unavailable"
        }}
  action:
    - choose:

        # The code should be added to the lock's slot
        - conditions:
            - condition: template
              value_template: "{{ is_state('binary_sensor.active_LOCKNAME_TEMPLATENUM','on') }}"
          sequence:
            - service: keymaster.add_code
              data_template:
                entity_id: LOCKENTITYNAME
                code_slot: >-
                  {{ TEMPLATENUM }}
                usercode: >-
                  {% set object = states('input_text.LOCKNAME_pin_TEMPLATENUM') %}
                  {{ object.strip() }}

        # The code should be removed from the lock's slot
        - conditions:
            - condition: template
              value_template: "{{ is_state('binary_sensor.active_LOCKNAME_TEMPLATENUM','off') }}"
          sequence:
            - service: keymaster.clear_code
              data_template:
                entity_id: LOCKENTITYNAME
                code_slot: >-
                  {{ TEMPLATENUM }}

################  binary_sensor: #################  
binary_sensor:

- platform: template
  sensors:

    active_LOCKNAME_TEMPLATENUM:
      friendly_name: "Desired PIN State"
      value_template: >-
        {## This template checks whether the PIN should be considered active based on ##}
        {## all of the different ways the PIN can be conditionally enabled/disabled ##}

        {## Get current date and time ##}
        {% set now = now() %}

        {## Get current day of week, date (integer yyyymmdd), and time (integer hhmm) ##}
        {% set current_day = now.strftime('%a')[0:3] | lower %}
        {% set current_date = now.strftime('%Y%m%d') | int %}
        {% set current_time = now.strftime('%H%M') | int %}

        {## Get whether date range toggle is enabled as well as start and end date (integer yyyymmdd) ##}
        {## Determine whether current date is within date range using integer (yyyymmdd) comparison ##}
        {% set is_date_range_enabled = is_state('input_boolean.daterange_LOCKNAME_TEMPLATENUM', 'on') %}
        {% set start_date = states('input_datetime.start_date_LOCKNAME_TEMPLATENUM').replace('-', '') | int %}
        {% set end_date = states('input_datetime.end_date_LOCKNAME_TEMPLATENUM').replace('-', '') | int %}
        {% set is_in_date_range = (current_date >= start_date and current_date <= end_date) %}
    
        {## Get current days start and end time (integer hhmm). Assume time range is considered enabled if start time != end time. ##}
        {## If time range is inclusive, check if current time is between start and end times. If exclusive, check if current time is before start time or after end time. ##}
        {% set current_day_start_time = (states('input_datetime.' + current_day + '_start_date_LOCKNAME_TEMPLATENUM')[0:5]).replace(':', '') | int %}
        {% set current_day_end_time = (states('input_datetime.' + current_day + '_end_date_LOCKNAME_TEMPLATENUM')[0:5]).replace(':', '') | int %}
        {% set is_time_range_enabled = (current_day_start_time != current_day_end_time) %}
        {% set is_time_range_inclusive = is_state('input_boolean.' + current_day + '_inc_LOCKNAME_TEMPLATENUM', 'on') %}
        {% set is_in_time_range = (
          (is_time_range_inclusive and (current_time >= current_day_start_time and current_time <= current_day_end_time))
          or
          (not is_time_range_inclusive and (current_time < current_day_start_time or current_time > current_day_end_time))
        ) %}

        {## Get whether code slot is active and current day is enabled ##}
        {% set is_slot_enabled = is_state('input_boolean.enabled_LOCKNAME_TEMPLATENUM', 'on') %}
        {% set is_current_day_enabled = is_state('input_boolean.' + current_day + '_LOCKNAME_TEMPLATENUM', 'on') %}

        {## Check if access limit is enabled and if there are access counts left. ##}
        {% set is_access_limit_enabled = is_state('input_boolean.accesslimit_LOCKNAME_TEMPLATENUM', 'on') %}
        {% set is_access_count_valid = states('input_number.accesscount_LOCKNAME_TEMPLATENUM') | int > 0 %}

        {## Code slot is active if slot is enabled + current day is enabled + date range is not enabled or current date is within date range ##}
        {## + time range is not enabled or current time is within time range (based on include/exclude) + access limit is not enabled or there are more access counts left ##}
        {{
          is_slot_enabled and is_current_day_enabled
          and
          (not is_date_range_enabled or is_in_date_range)
          and
          (not is_time_range_enabled or is_in_time_range)
          and
          (not is_access_limit_enabled or is_access_count_valid)
        }}

    pin_synched_LOCKNAME_TEMPLATENUM:
      friendly_name: 'PIN synchronized with lock'
      value_template: >
        {% set lockpin = states('sensor.LOCKNAME_code_slot_TEMPLATENUM').strip()  %}
        {% set localpin = states('input_text.LOCKNAME_pin_TEMPLATENUM').strip()  %}
        {% set pin_active = is_state('binary_sensor.active_LOCKNAME_TEMPLATENUM', 'on')  %}
        {% if lockpin == "0000" %}
        {%   set lockpin = "" %}
        {% endif %}
        {% if pin_active %}
          {{ localpin == lockpin }}
        {% else %}
          {{ lockpin == "" }}
        {% endif %}

###################  sensor:  ####################  
sensor:

- platform: template
  sensors:

    connected_LOCKNAME_TEMPLATENUM:
      friendly_name: "PIN Status"
      value_template: >-
        {% set pin_active = is_state('binary_sensor.active_LOCKNAME_TEMPLATENUM', 'on')  %}      
        {% set synched = is_state('binary_sensor.pin_synched_LOCKNAME_TEMPLATENUM', 'on')  %}      
        {% if pin_active %}
          {% if synched %}
            Connected
          {% else %}
            Connecting
          {% endif %}
        {% else %}
          {% if synched %}
            Disconnected
          {% else %}
            Disconnecting
          {% endif %}
        {% endif %}
      icon_template: >
        {% set pin_active = is_state('binary_sensor.active_LOCKNAME_TEMPLATENUM', 'on')  %}      
        {% set synched = is_state('binary_sensor.pin_synched_LOCKNAME_TEMPLATENUM', 'on')  %}      
        {% if pin_active %}
          {% if synched %}
            mdi:folder-key
          {% else %}
            mdi:folder-key-network
          {% endif %}
        {% else %}
          {% if synched %}
            mdi:folder-open
          {% else %}
            mdi:wiper-wash
          {% endif %}
        {% endif %}
