generate_package:
  description: Generate lock manager files.
  fields:
    lockname:
      description: Lock name to generate files for.
      example: frontdoor
      required: false
      selector:
        text:

add_code:
  description: Add code to lock. Supports ozw and zwave locks.
  target:
    entity:
      domain: lock
  fields:
    code_slot:
      description: The code slot you are attempting to add/replace a code into
      example: 2
      required: true
      selector:
        text:
    usercode:
      description: The code you are attempting to set
      example: 1234
      required: true
      selector:
        text:
      
clear_code:
  description: Clear code from lock. Supports ozw and zwave locks.
  target:
    entity:
      domain: lock
  fields:
    code_slot:
      description: The code slot you are attempting to clear
      example: 2
      selector:
        text:

refresh_codes:
  description: Refresh lock codes from the lock. 
  target:
    entity:
      domain: lock
