name: "Validation And Formatting"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate_hacs:
    name: "HACS Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
  validate_hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: home-assistant/actions/hassfest@master
