---
name: Yarn lint and build

on:
  push:
    branches: [beta, main]
    paths:
      - "**.js"
      - "**.ts"
      - "lovelace_strategy/**"
      - ".eslintrc.cjs"
      - "package.json"
      - "rollup.config.js"
      - "tsconfig.json"
  pull_request:
    branches: [beta, main]
    paths:
      - "**.js"
      - "**.ts"
      - "lovelace_strategy/**"
      - ".eslintrc.cjs"
      - "package.json"
      - "rollup.config.js"
      - "tsconfig.json"

jobs:
  yarn:
    name: Yarn lint and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "lts/iron"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Lint
        run: |
          yarn lint:fix
      - name: Check for changes from lint
        id: change_lint
        run: echo "changed=$(git status --porcelain | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Check if clean from lint
        if: steps.change_lint.outputs.changed != 0
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.setFailed('Repo is dirty after lint! Run yarn lint:fix locally.')
      - name: Build
        run: |
          yarn build
      - name: Check for changes from build
        id: change_build
        run: echo "changed=$(git status --porcelain | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Check if clean from build
        if: steps.change_build.outputs.changed != 0
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            core.setFailed('Repo is dirty after build! Run yarn build locally.')
